#pragma once
#include "BloomReverbEffect.h"
#include "CosmosisEffect.h"
#include "LostInSpaceEffect.h"
#include "RepeaterEffect.h"
#include "RhythmicDelayEffect.h"
#include "SubtractiveSynthEffect.h"
#include "TemporalCollapseEffect.h"
#include "TheFullRackEffect.h"
